/* Database schema to keep the structure of entire database. */

CREATE TABLE ANIMALS (ID INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1), NAME VARCHAR(30), DATE_OF_BIRTH DATE, ESCAPE_ATTEMPTS INTEGER, NEUTERED BOOLEAN, WEIGHT_KG Decimal)
ALTER TABLE animals ADD species varchar(255);
